name: Gitleaks scan local

on:
  pull_request:
    branches:
      - main
  
jobs:
  scan:
    name: Gitleaks scan local
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: '--config .gitleaks.toml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
